https://developers.liveperson.com:
  type: upstream
  upstream: jekyll_app:http

https://{default}/:
  type: upstream
  redirects:
    paths:
      "/events":
         to: "https://{default}/events.html"
         prefix: false
