https://developers.liveperson.com:
  type: upstream
  upstream: jekyll_app:http

https://{default}/events:
  type: upstream
  upstream: jekyll_app:http
  redirects:
    paths:
      "/events":
         to: "https://{default}/events.html"
